version: 2

jobs:
    build:
        working_directory: ~/repo

        docker:
            - image: circleci/node:10.18.1

        steps:
            - checkout
            - restore_cache:
                  key: dependency-cache-{{ checksum "package.json" }}
            - run:
                  name: Install Dependencies
                  command: npm install
            - save_cache:
                  key: dependency-cache-{{ checksum "package.json" }}
                  paths:
                      - ./node_modules
            - run: mkdir ~/repo/junit
            - run:
                name: Test
                command: |
                    echo "API-Gateway Test Suite"
                    npm run test -- --ci --runInBand --reporters=default --reporters=jest-junit
            - store_artifacts:
                path: ~/repo/junit
            - store_test_results:
                path: ~/repo/junit



workflows:
    version: 2
    build-deploy:
        jobs:
            - build