name: Release
on:
    push:
        branches:
            - master
jobs:
    publish:
        name: Run Release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '10.18.1'

            - name: Install Dependencies
              run: yarn install

            - name: Run Build
              run: yarn build

            - name: Publish Release
              run: yarn release
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
